### ISSUE TITLE
Add DataSource.deleteX(Collection) or similar

### ISSUE THREAD

**Issue by kuzi117** [CMPUT301W15T07/TravelTracker#113]
As it stands we can only delete single objects from the datasource in each callback. If we need to delete multiple items (`Claims`, `Items`, `Tags`) we must submit a request to the `DataSource` to delete each one which causes multiple updates, which @ryant26 notes causes flickering. `MultiCallback` doesn't solve this since it really just executes multiple callbacks. 

Closing this issue would involve creating a `DataSource.deleteX(Collection<X> xs)` for each of `Claim`, `Item` and `Tag`. `User`s might need one too, but there's currently no way to delete `User`s so the usefullness is debatable. This delete should fire only one update after deleting all items.

Error handling needs to be discussed:
 * Fail on one requested element not being in the existing list (i.e. if one item requested to be deleted isn't there then nothing is deleted)
 * Delete everything that exists and warn about ones that don't
 * Delete everything that exists and don't warn about the ones that don't

**Comment by kuzi117** [comment]
If it's still unclaimed I can do this when I start get back to working again. Also my vote for error handling goes to point 2, unless someone has a better solution that isn't there.

**Comment by TheLastBanana** [comment]
Hm. This is a bit of a tricky problem (and one I haven't really addressed in MultiCallback either). If you delete five things and the first two are deleted before the transaction fails, how do you recover? You'd have to know that the first two are now gone so that you can only queue the last three for deletion.

**Comment by kuzi117** [comment]
So solution one is probably the safest. Something like:
```
for(X x : xCollection) {
  if(!xsInMemory.contains(x)) {
    callback.onError("Everything is bad, but " + x.toString() + " in particular.");
    return;
  }
}
...
callback.onResult(null);
```
which completely avoids any sort of partial delete. If we're worried about stuff going wrong then this is what we should do.

**Comment by TheLastBanana** [comment]
Yeah, that's reasonable.

**Comment by kuzi117** [comment]
Ok. I feel like this is a big enough change where I'll wait an hour or so and hope to get some feedback from @kdbanman to see if something like this works in the ES/caching world, and others if they disagree with option 1.

**Comment by kdbanman** [comment]
Option 3 (or anything involving no warnings/messages) isn't necessary - it's easy enough to notify the user and I'm pretty sure that's preferred.  *Between Options 1 and 2, is one of them a preferred user experience?  Or is it purely ease of implementation that we're worried about?*

Regardless, I want to make sure I understand the issue.  Say the user queues up 3 (editable) claims for deletion while they are offline on one device, then changes one of them on another device before the first device syncs up.  The changes with the later time stamp will be preferred.

*Option 1 would mean that all 3 queued deletions would be ignored because of the 1 that was overridden, correct?*

*And Option 2 would mean that only the 1 would fail to delete, but the other two would go away just fine?*

If that's the case, Option 2 is easier to implement (no concept of operation groups for the cache to worry about).

**Comment by kdbanman** [comment]
Maybe it'd be good to throw down some context to make sure I'm not breaking assumptions.  **Read if you feel like it.**  This will mostly be class documentation of the cache class anyways.

The caching datasource will have a bunch of `HashMap<UUID, Document subclass>`, just like the in memory data source.  Those hash maps are for the Document objects that the Views and Controllers refer to.

- The cache will try to run save or delete with the ES server every time those in memory documents change (possibly capped at once per second or something).
- If a save fails due to no connection, it will add the document id to a queue of to-save documents, and save the changed (dirty) document to a local file
- If a delete fails due to no connection, it will add the document id to a queue of to-delete documents,  and save the deleted document to a local file (it's saved to use the document last changed timestamp for conflict resolution upon reconnection)
- If a save or delete fails for another reason, I don't think this is very recoverable, so the user will be notified but I'm not quite sure what to do here yet.

The to-save and to-delete lists will be stored in local files, and the CacheDataSource will look for them and use them when being constructed, in case the app closed before reconnecting with the server.

When the caching datasource reconnects to the ES server, it'll try to save the documents in the to-save list, and try to delete the documents in the to-delete list.  I say "try" because the cache will need to pull from the server all documents from the two lists, and only run the save/delete if the local last change timestamp is more recent than the remote last change timestamp.

Whew.

**Comment by kuzi117** [comment]
Oh dear god. I hadn't even really thought about it like that. It's easy enough in the InMemoryDataSource to do option 1, but I guess we can't really revert entire things once we get to caching and ES. I guess really at this point we should be designing with ES in mind since any of the three options are doable in the InMemoryDataSource.

**Comment by kuzi117** [comment]
I'm downgrading this to low, it's less pressing than some of the other stuff.

Frankly I'm almost ready to mark this as won't fix since it's more likely to cause breaking that we won't be able to fix this close to project end. Anyone else?

**Comment by kdbanman** [comment]
Do batch deletions currently work on the ui side with a loop or something?

**Comment by kuzi117** [comment]
Yeah, see [ClaimsList](https://github.com/CMPUT301W15T07/TravelTracker/blob/master/src/cmput301w15t07/TravelTracker/activity/ClaimsListActivity.java#L197) or [ItemsList](https://github.com/CMPUT301W15T07/TravelTracker/blob/master/src/cmput301w15t07/TravelTracker/activity/ExpenseItemsListActivity.java#L229).

**Comment by kdbanman** [comment]
well these methods will be pretty easy to implement.  I'll do the refactor after CacheDataSource is working.  I'm so close...

**Comment by kuzi117** [comment]
No worries, I think it's fairly low priority. Even if you do want to do it, it might be a better idea to close some other issues rather creating something else we need to test.

**Comment by kdbanman** [comment]
we no longer have time to make this refactor and test it.  especially with how insane delete calls are with ES.
