### ISSUE TITLE
ExpenseItemInfoActivity fields constantly losing focus to the amounts field

### ISSUE THREAD

**Issue by kuzi117** [CMPUT301W15T07/TravelTracker#114]
Everytime a character is typed into the description field the amount field gains focus. Less noticeable (doesn't affect usability) is the spinners doing the same thing. After selecting something from a spinner the amount field gains focus again where the spinner field should still have it.

Repro:
 1. Open the expense item info activity
 2. Type into amount field
 3. See amount field not lose focus

Repro:
 1. Open the expense item info activity
 2. Type into description field
 3. See amount field gain focous after 1 character

Repro:
 1. Open the expense item info activity
 2. Pick something from spinner
 3. See amount field gain focus despite not being clicked

**Comment by therabidsquirel** [comment]
I noticed in the xml for the layout there's a line that makes the amount field request focus upon starting the activity, and I wondered if that had something to do with it. Removing the line does nothing though, as typing into the description field then for example just causes it to lose focus and nothing to gain focus.

**Comment by skwidz** [comment]
I can take a look at this after my lab exam tonight.

**Comment by skwidz** [comment]
I figured this one out, it was updating the Item data everytime the text in the field changed, which was causing the fields to lose focus, then the RequestFocus tag in the xml was giving the focus back to the amount

**Comment by skwidz** [comment]
im going to reopen this as its now not saving if the field still has focus and the user backs out of the activity

**Comment by kuzi117** [comment]
Persevere, friend. If I finish my tests I can have a look.

**Comment by therabidsquirel** [comment]
ExpenseItemInfo seems to crash a lot for me now. Sometimes upon entering the activity, sometimes upon editing fields while in it. Every time it crashes though the error says there's a null pointer exception on [this line](https://github.com/CMPUT301W15T07/TravelTracker/blob/master/src/cmput301w15t07/TravelTracker/activity/ExpenseItemInfoActivity.java#L197). I've restarting and refreshing both eclipse and the emulator several times to no success. I'm not sure what's going on.

**Comment by skwidz** [comment]
Yeah I know. I thought i reverted the commit but I guess it only changes my local branch.

**Comment by therabidsquirel** [comment]
I'm updating this to high at this point as I feel it's very important for expense item editing.

**Comment by skwidz** [comment]
so what seems to be happening is actionUp keyEvents (as they are called) are being generated for some reason, and these are pushing the focus up to the back button at the top left of the screen. 

Why? no freaking idea. 

I think im just going to make fragments for changing the description and the amount because im sick of dealing with this bug.

**Comment by therabidsquirel** [comment]
Can't you just disable the events on the EditText fields?

**Comment by skwidz** [comment]
Im not sure how i would go about disabling the events
i guess i could try and catch the individal events and then just do nothing. 
not sure reall how i would do it as the events are happening, but the emulator is telling me the key isnt down. which makes sense. 



Is this happening on peoples phones at all?

**Comment by therabidsquirel** [comment]
Could something similar to [this](https://github.com/CMPUT301W15T07/TravelTracker/blob/master/src/cmput301w15t07/TravelTracker/util/DestinationEditorFragment.java#L163) work? Except checking event to KeyEvent.ACTION_UP?

**Comment by therabidsquirel** [comment]
It'd be helpful if we knew exactly when this started happening, so we could compare commits.

**Comment by skwidz** [comment]
yeah no kidding, im a perfect world we would just be able to quickly cycle trough commits and see where errors starteed poppng up

i dont think its the key events anymore, i thkn those are just generated because the keyboard kys are being pressed when the user types, and i dont thi tey are actually changing th focus. Disabling the keys didnt have any apparent effect apart from diabling those specific keyboard keys. 

Im  going to continue with these fragments.

**Comment by therabidsquirel** [comment]
I looked at the history of ExpenseItemInfoActivity, and it looks like the problems started occuring after my commit f5598c4. Elliot had two minor commits 6 days before that that certainly couldn't have broken it, and then more start another 3 days earlier. I don't see anything in the history of ExpenseItemInfoActivity from before this issue was created that could possibly have broken anything.

**Comment by kuzi117** [comment]
This seems to be absent for me right now. I don't actually see what's fixed it in the history, so I'm wondering if there's a bug in the bug. Can someone else confirm?

**Comment by skwidz** [comment]
OK WHATEVER HOPE IT DOESNT COME BACK, GOOD JOB EVERYBODY

**Comment by therabidsquirel** [comment]
This still works fine with the commits I just pushed, so I'll close it. I still have no fricken idea why it happened in the first place, but we can reopen this if we see it again.

**Comment by skwidz** [comment]
i figured out why this went away. 

I think its because the activity isnt reloading the data when something is changed anymore, though it appears to be saving on any edits. 

it affects the receipt image mostly. if you delete the image, it doesnt disapear from the activity right away, but if you back out to the list its gone and when you return to the item info its gone from the item .
