### ISSUE TITLE
String Styles

### ISSUE THREAD

**Issue by kuzi117** [CMPUT301W15T07/TravelTracker#42]
So in my first project I used the strings.xml for every possible string.

I think this is how it's supposed to be done but I just want to confirm with the rest of the team.

**Comment by therabidsquirel** [comment]
I did the same, as Eclipse gave a warning for every hard-coded string otherwise. I do like it though. I know from a distribution standpoint it makes a lot of sense, as if you need to translate an app you just have to change all the values in strings.xml without changing any code or references or anything. Even though that won't be an issue for us, I still think it's a good idea.

**Comment by TheLastBanana** [comment]
Yeah, we should keep strings in strings.xml. We'll need to find a good way
to organize the file, though.

**Comment by kuzi117** [comment]
How would you prefer to organize it? Per activity if they're used directly in the layout xml and per class if they're used in code?

**Comment by TheLastBanana** [comment]
That sounds reasonable to me.

**Comment by kuzi117** [comment]
(Wiki'd and closed)[https://github.com/CMPUT301W15T07/TravelTracker/wiki/Style-Guide]
