### ISSUE TITLE
Create Release Plan

### ISSUE THREAD

**Issue by kuzi117** [CMPUT301W15T07/TravelTracker#6]
We need to create a roadmap for development.

Elliot and I are trying to be aggressive with our early development so that we don't have to deal with things right at crunch time later.

We'll transcribe everything into the milestones/issues in this tracker so you can look there. Will let you know when things are ready to be inspected.

**Comment by kdbanman** [comment]
awesome.  as Ryan and I create issues for each use case, do you want us to add them to milestones, or do you want to handle that?

**Comment by TheLastBanana** [comment]
Feel free to assign them to milestones! We should have them ready shortly.

**Comment by kuzi117** [comment]
I already moved over the use cases you had created already, but if you feel they deserve to be elsewhere feel free to move them.

**Comment by TheLastBanana** [comment]
Here are some tentative milestones. There are a few holes, so we'll fill them in soon.

## Project Part 3 (Feb. 14 - Feb. 23)
**Feb. 17**
Initial completed UML diagram of the app. Any concerns with the UML should be raised before the 18th.

**Feb. 18**
After this point, we will avoid major changes to the UML diagram so that implementation can start.

**Feb. 23**
Skeleton code of the offline portion of the model, including classes and method stubs. Some code can probably be reused from our solo assignments.

## Project Part 4 (Feb.24 - Mar. 16)
**Feb. 27**
Code review. Go over the current code base and make sure that style is consistent and Javadoc is being used properly.

***Use cases are implemented in here!***

**Mar. 13**
Code review. Go over the current code base and make sure that style is consistent and Javadoc is being used properly.

## Project Part 5 (Mar. 17 - Apr. 7)
**Mar. 24 (???)**
Power use estimation. Supposedly this happens in the second-to-last lab and some people come in with code to measure our apps, so we'll plan this when we have a better idea of when it's going to happen.

**Mar. 28**
Refactoring should start here. "Run the JDeodorant tool for suggesting potential refactorings in your design. Consider Implementing the refactorings (as deemed reasonable), and describe some of the refactorings (done and not done) in a separate page in your team wiki. At least 1 reasonable paragraph must be provided on the wiki."

**Mar. 31 (???)**
Project presentation (probably using a branch that isn't in the middle of being refactored). This will probably happen in the last lab. "Provide an engaging live demo. Do not play your demo video with audio. If it has audio, talk over it. Make sure your presentation is LIVE."

**Apr. 5**
Reuse statement. "Document instances of software reuse. Give proper credit to the original developers. Obtain approval for the use of third-party libraries as appropriate. Enter this information in your team wiki."

**Comment by kdbanman** [comment]
The repeated code reviews are a good idea.

**Comment by TheLastBanana** [comment]
I added milestones for ElasticSearch and the test fixture.

**Comment by therabidsquirel** [comment]
Closing for Braedy.
