### ISSUE TITLE
Exiting and restarting app.

### ISSUE THREAD

**Issue by therabidsquirel** [CMPUT301W15T07/TravelTracker#72]
Currently (from the UI diagram) when the user hits the back button from the Claims List screen the app will close, instead of backing to the Login screen. When they reopen the app, it takes them back to the Claims List screen as the same user. The only way to sign out would be to select the sign out option from any of the screens.

First, I think that it might be better (and easier) if hitting the back button from the Claims List screen will sign the user out and take them to the Login screen, and then hitting the back button from there will close the app. Reopening the app at anytime then would always start from the Login screen. I see positives to both:

- All the apps I can think of keep a user signed in unless they explicitly perform the sign out function. Having this consistency in our app was my original reason for adding it to the UI. If users will not change roles/names often, then it makes sense to remember what their last role/name was instead of prompting for them to reenter it every time they reopen the app.

- Signing out whenever the app closes is easier to code, and it's one less thing we'd have to worry about as it's not covered in the user stories. If users will change roles/names at least semi-often, it could be better to have them reenter it each time upon app start up.

Second, and I feel this has definitely been discussed before, if a user force closes the app (or it crashes) it should in a way act like backing out of the app (so they'd have to sign in again)?

I'd like to know what everyone else thinks, and if I should change the UI diagram.

**Comment by TheLastBanana** [comment]
First point: logging out by hitting "back" in the Claims List screen is fine for now. It's not a terribly complicated change to make later if we change our minds.

Second point: for the sake of consistency, we might as well.

For now, treating our app in a way that assumes a lot of logging in and out makes sense because you have to go back to the login screen to choose Claimant/Approver. So we might as well go whole hog with that. That said, maybe it would be good to save the last username entered so it's easier to log back in?

**Comment by therabidsquirel** [comment]
That I do like, saving the last username used.

**Comment by kdbanman** [comment]
> you have to go back to the login screen to choose Claimant/Approver. So we might as well go whole hog with that.

Whole hog indeed.
