### ISSUE TITLE
Should spinners in ExpenseItemInfoActivity have empty values?

### ISSUE THREAD

**Issue by therabidsquirel** [CMPUT301W15T07/TravelTracker#97]
Since the ItemCurrency and ItemCategory spinners are set from the enums, there are just the values we have in the enums. This means that upon creating a new expense item, the currency and category would have to default to something. Should we have some sort of blank they can default to in the spinner?

**Comment by kdbanman** [comment]
Specific:

I prefer initializing the object with sensible defaults within the model
object constructor.  Currency to CAD, category to something else. Maybe we
could add an UNCATEGORIZED to category.

General:

Sensible defaults and setters that guard against null setting should maybe
be an explicit feature of our model objects, so that our views can just
assume that getters never return null. Thoughts?

**Comment by therabidsquirel** [comment]
I agree with not having things in our model objects be null, that's what I meant by "some sort of blank". I think that'd make things easier to assume getters never return null.

I think UNCATEGORIZED or NO_CATEGORY or something is a good default for category. I don't think we really can have a non-currency default for currency though, given our ItemCurrency enum interacts with java.util.Currency. CAD would be an okay default I guess.

**Comment by kdbanman** [comment]
I guess if this were a production app, default currency could be location-aware.  But let's not.

**Comment by TheLastBanana** [comment]
Java's built-in Currency does let us find the currency for the current
locale, but since we're using a custom enum, that's going to be a pain. +1
for CAD.

**Comment by therabidsquirel** [comment]
I just added a category "No Category" (d7ef8b4).

**Comment by kdbanman** [comment]
:+1:
